### ISSUE TITLE
Porting to Julia 1.0

### ISSUE THREAD

**Issue by markaduol** [vtjeng/MIPVerify.jl#12]
I'm working on a similar piece of software in a different research group (not at MIT). For comparison purposes, I'd like to know whether there are any plans to port this package to Julia 1.0.

Thanks,
M

**Comment by vtjeng** [comment]
Thanks for asking. I am currently in the process of porting this to Julia 1.0. [1] Unfortunately, since this package relies on the [`JuMP`](https://github.com/JuliaOpt/JuMP.jl) package, we'll have to wait till the `JuMP` v0.19 release, since that's the first release of `JuMP` supporting Julia 1.0. 

I'll update this thread once the `MIPVerify` release supporting Julia 1.0 is available.

[1] You can track progress on this feature branch: https://github.com/vtjeng/MIPVerify.jl/tree/feature/JuMP-0.19-compatibility.

**Comment by vtjeng** [comment]
Sorry for the long wait, but this is finally closed via #18. Let me know if you're having trouble using the package in Julia 1.0.
