### ISSUE TITLE
Problem with very sparse network

### ISSUE THREAD

**Issue by darioguidotti** [vtjeng/MIPVerify.jl#32]
Hello,

I am using MIPVerify to test the robustness of very sparse networks (i.e., in which many of the weights are 0 or near to 0, for example, 10^-8).

When I test this kind of networks with MIPVerify in some cases it gives an error and returns an array of NaN values.

May it be possible that this error is due to a problem in the 
conditioning of the matrixes of the MILP problem caused by the sparsity of the networks?

In attachment, you can find a .zip in which I have set up some script in order to reproduce the issue.

Thank you for your time!

[mip_test.zip](https://github.com/vtjeng/MIPVerify.jl/files/4184555/mip_test.zip)

**Comment by vtjeng** [comment]
Thanks for your detailed issue. I'll take a closer look at the contents of the zip file when I have time, but in the meantime it is a known issue that having input weights which are small (relative to the largest weights) _but non-zero_ leads to issues in the numerical methods used by the underlying solver (Gurobi, CPLEX or similar). 

(In my experience, having sparse networks with weights _exactly_ zero will actually help with solve times --- see the Appendix H to the paper linked in the README for some numerical details).

If you are able to retrain the network with a regularization term in the loss to encourage sparsity (a small L1 penalty on weights forces weights to be zero in my experience) that will help with verification. Otherwise, is it possible to round those small values to zero?

**Comment by darioguidotti** [comment]
Thank you for your response!
I will modify my networks as recommended, thank you again for your help!

**Comment by vtjeng** [comment]
Moving this to a discussion in https://github.com/vtjeng/MIPVerify.jl/discussions/157.
