### ISSUE TITLE
Input bounds support

### ISSUE THREAD

**Issue by samuelemarro** [vtjeng/MIPVerify.jl#40]
Does MIPVerify support input bounds? For example, I'd like to restrict the space of valid adversarial examples to [0, 1] (i.e. valid images). Is this type of constraint supported?

**Comment by vtjeng** [comment]
There isn't a clean way to specify input bounds in a generic fashion right now, but if you're looking to restrict it to the space of valid images in `[0, 1]`, we currently do already do that for all the types of perturbation families (`UnrestrictedPerturbationFamily, BlurringPerturbationFamily, LInfNormBoundedPerturbationFamily`).

For the `UnrestrictedPerturbationFamily` and the `LInfNormBoundedPerturbationFamily`, `v_e` is the matrix of variables corresponding to the perturbation, and `v_x0` is the matrix of variables corresponding to the perturbed input.

### `UnrestrictedPerturbationFamily`
https://github.com/vtjeng/MIPVerify.jl/blob/b8489c8da0def7357713d48a5d59bc527e0e317f/src/models.jl#L173-L174

### `LInfNormBoundedPerturbationFamily`
https://github.com/vtjeng/MIPVerify.jl/blob/b8489c8da0def7357713d48a5d59bc527e0e317f/src/models.jl#L241-L242

### `BlurringPerturbationFamily`
For the `BlurringPerturbationFamily`, the perturbation is in the form of a blurring filter `v_f`:

https://github.com/vtjeng/MIPVerify.jl/blob/b8489c8da0def7357713d48a5d59bc527e0e317f/src/models.jl#L209-L211

If you'd like to specify different bounds on the input (e.g. [0, 255] instead of [0, 1]), you'll have to modify the bounds specified here. (You'll have to modify the source code directly). Let me know if you have any questions.

**Comment by samuelemarro** [comment]
Thank you for your help!
