### ISSUE TITLE
Does building a model for each input improve performance?

### ISSUE THREAD

**Issue by samuelemarro** [vtjeng/MIPVerify.jl#79]
Model caching's deprecation made me wonder: does building the model once and reusing it for other inputs lead to worse performance compared to just rebuilding the model for each input?

**Comment by vtjeng** [comment]
You shouldn't have seen any difference in performance whether or not the models were cached. (You do save on the time to compute bounds if using a cached model). 

Under the hood, what happened (when the option to use cached models was available) is that we would compute a hash based on the constraints on the network input (but not any parameters that don't affect the bounds, such as the target label or tolerances). Cached models are referenced via the hash. 

When users specify unbounded perturbations (`UnboundedPerturbationFamily`), the models generated would be reused in all cases, since the constraints on the network input are exactly the same. However, when users specify bounded perturbations (e.g. `LInfNormBoundedPerturbationFamily`), the model hash is only the same (and the model is reused) if the nominal input (i.e. the model that we are perturbing) is the same. Note that models are still reused if only the target label is changed.

Let me know if you have any other questions.

**Comment by samuelemarro** [comment]
Thank you for your help, I'll close the issue!
